// GENERATED CODE - DO NOT MODIFY BY HAND.
// ignore_for_file: type=lint
// Generated by vrt_preview_builder.

import 'package:flutter/material.dart';

import 'foundation/preview.dart';
import 'package:widget_previewer_lab/src/presentation/screens/home/home_preview.dart'
    as _i1;
import 'package:widget_previewer_lab/src/presentation/screens/preview_gallery/preview_gallery_preview.dart'
    as _i2;
import 'package:widget_previewer_lab/src/presentation/screens/result_summary/result_summary_preview.dart'
    as _i3;

final List<VrtPreviewEntry> visualRegressionPreviews = [
  VrtPreviewEntry(
    vrtFileName: 'home_mobile',
    group: 'Home',
    name: 'Mobile layout',
    size: Size(390, 760),
    builder: _i1.homeMobilePreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'preview_gallery_mobile',
    group: 'PreviewGallery',
    name: 'Mobile layout',
    size: Size(390, 760),
    builder: _i2.previewGalleryMobilePreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'preview_gallery_tablet',
    group: 'PreviewGallery',
    name: 'Tablet layout',
    size: Size(760, 640),
    builder: _i2.previewGalleryTabletPreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'result_summary_interactive_mobile',
    group: 'ResultSummary',
    name: 'Interactive mobile',
    size: Size(390, 760),
    builder: _i3.resultSummaryInteractiveMobilePreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'result_summary_in_progress_mobile',
    group: 'ResultSummary',
    name: 'In progress mobile',
    size: Size(390, 760),
    builder: _i3.resultSummaryInProgressMobilePreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'result_summary_completed_mobile',
    group: 'ResultSummary',
    name: 'Completed mobile',
    size: Size(390, 760),
    builder: _i3.resultSummaryCompletedMobilePreview,
  ),
  VrtPreviewEntry(
    vrtFileName: 'result_summary_attention_mobile',
    group: 'ResultSummary',
    name: 'Attention mobile',
    size: Size(390, 760),
    builder: _i3.resultSummaryAttentionMobilePreview,
  ),
];
